src/healthnet/base/urls.py
from django.conf.urls import url

from . import views

"""
    @description: The Landing Page for the HealthNet Application
"""
urlpatterns = [
    url(r'^$', views.redirectLanding),
    url(r'^home/$', views.landingPage, name='landing'),
]

src/healthnet/healthnet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^healthnet/', include([     # Branches everything off of "healthnet/"
            # Site landing page
        url(r'', include('base.urls', namespace='base')),
            # Viewing the system log
        url(r'^system/log/', include('viewLog.urls', namespace='systemLog')),
            # Register users
        url(r'^register/', include('register.urls', namespace='register')),
            # Profile Functionality
        url(r'^profile/', include('userprofile.urls', namespace='profile')),
            # Appointment Functionality
        url(r'^apt/', include('appointment.urls', namespace='appointment')),
            # Medical History functionality
        url(r'^medical/', include('medicalHistory.urls',namespace='medical')),
            # Hospital Functionality
        url(r'^hospital/', include('hospital.urls', namespace='hospital')),
            # Admin Interface
        url(r'^admin/', include(admin.site.urls)),
        url(r'^prescription/', include('prescription.urls', namespace='prescription')),
            # Patient list functionality
        url(r'^patients/', include('patient.urls', namespace='patient')),
        url(r'^messages/', include('messaging.urls', namespace='messages')),
        url(r'^results/', include('testResults.urls', namespace='results')),
    ])),
    url(r'^$', views.redirectLanding),
    url(r'^admin/$', views.redirectAdmin),
]
if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, })]

src/healthnet/hospital/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.hospitalRedirect),
    url(r'^create/$', views.createHospital, name='create'),
    url(r'^view/$', views.viewHospitals, name='view'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.updateHospital.as_view(), name='update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.deleteHospital, name='delete'),
]

src/healthnet/patient/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^patientList/$', views.patientList, name='patientList'),
    url(r'^admit/(?P<pk>[0-9]+)/$',views.admitPatient, name='admitPatient'),
    url(r'^patientInfo/(?P<pk>[0-9]+)/$', views.viewPatientDetails, name='patientDetails'),
    url(r'^admitted/$', views.admittedPatients, name='admittedPats'),
    url(r'^discharge/(?P<pk>[0-9]+)/$', views.dischargePatient, name='discharge'),
    url(r'^transferSuccess/([0-9]+)/$', views.transferPatient, name='transferPatient'),
    url(r'^transferFailed/([0-9]+)/$', views.transferFailed, name='cannotTransfer'),
]

src/healthnet/register/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^admin/$', views.createAdmin, name='createAdmin'),
    url(r'^patient/$', views.createPatient, name='createPatient'),
    url(r'^doctor/$', views.createDoctor, name='createDoctor'),
    url(r'^nurse/$', views.createNurse, name='createNurse'),
]

src/healthnet/viewLog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.listLog, name='log'),
    url(r'^(?P<reverseTime>\d{1})/(?P<startDay>\d{8})/(?P<endDay>\d{8})/$', views.listLog, name='log'),

    url(r'^stats/$', views.stats, name='stats'),
    url(r'^stats/(?P<startDay>\d{8})/(?P<endDay>\d{8})/$', views.stats, name='stats'),
    url(r'^stats/(?P<startDay>\d{8})/(?P<endDay>\d{8})/(?P<hospital>[0-9]+)/$', views.stats, name='stats'),

    url(r'^filter/$', views.filterLog, name='filter'),
    url(r'^stats/filter/$', views.filterStats, name='filterStats'),
]

src/healthnet/base/models.py
"""
    Application: HealthNet
    File: models.py
    Authors:
        - Nathan Stevens
        - Philip Bedward
        - Daniel Herzig
        - George Herde
        - Samuel Launt

    Description:
        - This file contains all the class definitions for each
          model within the HealthNet application
"""
from django.conf import settings
from django.db import models
from django.db import signals
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _  # import ugettext as an underscore
import datetime

AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')


class Person(models.Model):
    """
    @class: Person
    @description: A person, who has registered to use the HealthNet
                  application.  A Person may be a Doctor, Nurse, or
                  Patient.
    @Primary Key: SSN - the person's Social Security Number
    @Relationships:
                - Person can be a Patient, Doctor, or Nurse
    """
    id = models.AutoField(primary_key=True)
    ssn = models.PositiveIntegerField()
    user = models.OneToOneField(User)
    # Make a name field with a max_length of 100 characters
    birthday = models.DateField()
    phoneNumber = models.PositiveIntegerField()

    def __str__(self):
        """
        @description: returns a string for First and Last name
        """
        return '%s %s' % (self.user.first_name, self.user.last_name)

    def get_absolute_url(self):
        return reverse('person-detail', kwargs={'pk': self.pk})


class Doctor(models.Model):
    """
    @class: Doctor
    @description: A Doctor has specific permissions within the HealthNet
                  application.
    @Primary Key: id - auto-generated
    @Relationships:
                - personID - the Doctor is a Patient
                - patientID - A Doctor has many patients
    """
    id = models.AutoField(primary_key=True)
    licenseNumber = models.PositiveIntegerField()
    specialty = models.CharField(max_length=200, blank=True)
    hospitalID = models.ForeignKey('Hospital', to_field='id')
    personID = models.ForeignKey('Person', to_field='id')
    patients = models.ManyToManyField('Patient', blank=True)
    addressID = models.ForeignKey('Address', to_field='id')

    def __str__(self):
        return '%s' % (self.personID.__str__())


class Nurse(models.Model):
    """
    @class: Nurse
    @description: A Nurse, has specific permissions within the HealthNet
                  application.  Nurse is a person.
    @Primary Key: Id, auto-generated.
    @Relationships:
                - personID - A Nurse is a Person
                - hospitalID - A Nurse has a Hospital
    """
    id = models.AutoField(primary_key=True)
    license_number = models.PositiveIntegerField()
    department = models.CharField(max_length=300)
    personID = models.ForeignKey('Person', to_field='id')
    hospitalID = models.ForeignKey('Hospital', to_field='id')
    addressID = models.ForeignKey('Address', to_field='id')

    def __str__(self):
        return '%s' % (self.personID.__str__())


class Patient(models.Model):
    """
    @class: Patient
    @description: A Patient, is one of the most active actors within the
                  HealthNet application.  A Patient is a Person.
    @Primary Key: Id, auto-generated.
    @Relationships:
                - personID - A Patient is a Person
                - addressID - A Patient has an Address
                - insuranceID - A Patient has Insurance
                - emergencyContactID - A Patient has an Emergency Contact
    """
    id = models.AutoField(primary_key=True)
    personID = models.ForeignKey('Person', to_field='id')
    addressID = models.ForeignKey('Address', to_field='id')
    insuranceID = models.ForeignKey('Insurance', to_field='id')
    emergencyContactID = models.ForeignKey('EmergencyContact', to_field='id')
    hospitalID = models.ForeignKey('Hospital', to_field='id', null=True, blank=True, related_name='hospitalID')
    medicalID = models.ForeignKey('MedicalHistory', to_field='id', null=True, blank=True)
    preferredHospital = models.ForeignKey('Hospital', to_field='id', null=True, blank=True,
                                          related_name='preferredHospital')

    """
        @description: returns a string of the Patient's id
    """

    def __str__(self):
        return '%s' % (self.personID.__str__())


class Root(models.Model):
    """
    @class: Root
    @description: A Root user has the highest level permissions within
                  the application.
    @Primary Key: id - auto-generated
    """
    id = models.AutoField(primary_key=True)
    personID = models.ForeignKey('Person', to_field='id')


class Admin(models.Model):
    """
    @class: Admin
    @description: Admin role for application, has high level permissions
    @Primary Key: Id, auto-generated.
    @Relationships:
                - hospitalID - the Admin works at a Hospital
                - personID - Admin is a Person
    """
    id = models.AutoField(primary_key=True)
    hospitalID = models.ForeignKey('Hospital', to_field='id')
    personID = models.ForeignKey('Person', to_field='id')
    # addressID = models.ForeignKey('Address', to_field='id')


class Appointment(models.Model):
    """
    @class: Appointment
    @description: A Patient, and Doctor have an appointment with each other
    @Primary Key: Id, auto-generated.
    @Relationships:
                - doctorID - An Appointment has a Doctor
                - patientID - An Appointment has a Patient
    """
    id = models.AutoField(primary_key=True)
    doctorID = models.ForeignKey('Doctor', to_field='id')
    patientID = models.ForeignKey('Patient', to_field='id')
    aptDate = models.DateField()
    aptTime = models.TimeField()

    reason = models.CharField(max_length=300)

    def getPatient(self):
        return self.patientID

    def getHospital(self):
        return self.doctorID.hospitalID

    """
        @description: returns a string for an Appointment
    """

    def __str__(self):
        return 'Doctor: %s Patient: %s Date: %s Time: %s Reason %s' \
               % (self.doctorID, self.patientID, self.aptDate, self.aptTime, self.reason)


class ExtendedStay(models.Model):
    id = models.AutoField(primary_key=True)
    appointmentID = models.ForeignKey('Appointment', to_field='id')
    endDate = models.DateField()
    endTime = models.TimeField()

    def getPatient(self):
        return self.appointmentID.patientID

    def __str__(self):
        return "Patient: %s, admitted until %s at %s" % (self.getPatient(), self.endDate, self.endTime)


class Address(models.Model):
    """
    @class: Address
    @description: A Person and Hospital have an address where they reside
    @Primary Key: Id, auto-generated.
    @Relationships:
    """
    id = models.AutoField(primary_key=True)
    street = models.CharField(max_length=200)
    zip = models.PositiveIntegerField()
    # Todo: This is dropping '0's off the front of the value EX: 02043 -> 2043
    # Do we change this to a CharField to prevent the loss of values?
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=50)

    """
        @description: returns a string value of an address
    """

    def __str__(self):
        return '%s %s, %s %s' % (self.street, self.city, self.state, self.zip,)


class Insurance(models.Model):
    """
    @class: Insurance
    @description: An insurance company with policy number of a client to have
                  insurance coverage
    @Primary Key: Id, auto-generated
    @Relationships:
                - addressID - Insurance has an Address.
    """
    id = models.AutoField(primary_key=True)
    addressID = models.ForeignKey(Address, to_field='id')
    name = models.CharField(max_length=100)
    policyNumber = models.PositiveIntegerField()

    def __str__(self):
        return 'Company: %s Policy Number: %i' % (self.name, self.policyNumber)


class Hospital(models.Model):
    """
    @class: Hospital
    @description: Where a Doctor, Nurse, and Admin work.  A patient
                  receives healthcare at a Hospital
    @Primary Key: Id, auto-generated
    @Relationships:
                - addressID - Insurance has an Address.
                - doctorID - Hospital has many Doctors
    """
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    address = models.ForeignKey('Address', to_field='id', null=True)
    # MANY TO MANY RELATIONSHIP: HOSPITAL TO DOCTOR
    # A hospital has doctors
    # doctorID = models.ManyToManyField(Doctor)
    # Add nurse field
    # nurseID = models.ManyToManyField(Nurse)
    # patients = models.ManyToManyField(Patient)


    def __str__(self):
        """
        @description: Returns a string of the Hospital's name
        """
        return '%s' % (self.name)


class EmergencyContact(models.Model):
    """
    @class: EmergencyContact
    @description: When a Patient registers they must list an EmergencyContact
                  in case of an Emergency.
    @Primary Key: Id, auto-generated
    @Relationships:
                - personID - An EmergencyContact is a Person
    """
    id = models.AutoField(primary_key=True)
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)
    emergencyNumber = models.PositiveIntegerField()
    personID = models.ForeignKey('Person', to_field='id', default=None, null=True)

    """
        description: Returns a String of an EmergencyContact
    """

    def __str__(self):
        return 'Emergency: %s %s' % (self.firstName, self.lastName)


class MessageManager(models.Manager):
    def inbox_for(self, user):
        """
        Returns all messages that were received by the given user
        and are not marked as deleted
        """
        return self.filter(
            recipient=user,

src/healthnet/base/views.py
from django.contrib.auth.decorators import user_passes_test
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
import logging

logger = logging.getLogger(__name__) 


# Create your views here.
def group_required(*group_names):
    """Requires user membership in at least one of the groups passed in."""

    def in_groups(u):
        if u.is_authenticated():
            if bool(u.groups.filter(name__in=group_names)) | u.is_superuser:
                return True
        return False

    return user_passes_test(in_groups)


def landingPage(request):
    logger.info(str("Landing Page accessed"))
    return render(request, 'index.html', {})


def redirectLanding(request):
    return redirect(reverse('base:landing'), permanent=True)

src/healthnet/base/templates/base/navbar.html
{% load staticfiles %}
{% load app_filters %}

<DOCTYPE html>

    <html lang="en">
    <head>
        <meta charset="UTF-8">

        <!-- Universal styling -->
        <link type='text/css' href="{% static 'css/bootstrap.css' %}" rel='stylesheet'>
        <link type='text/css' href="{% static 'css/navbar.css' %}" rel='stylesheet'>
        <link type='text/css' href="{% static 'css/utilities.css' %}" rel='stylesheet'>

        <!-- Fonts -->
        <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

        <!-- Begin block for page specific CSS -->
        {% block style %}
        {% endblock %}
    </head>
    <body>

    <!-- Checks to see if the user is logged in -->
    {% if user.is_authenticated %}

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" data-item="home" href="{% url 'profile:userLogin' %} ">HealthNet</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <!-- <li data-item="home"><a href="{% url 'profile:userLogin' %}">Home</a></li> -->
                    {% if not request|isRoot or request|isAdmin %}
                    <li class="dropdown" data-item='appointments'>

                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false"> Appointments
                            <span class="caret"></span></a>

                        <ul class="dropdown-menu">
                            <li><a href="{% url 'appointment:view' %}">View your appointments</a></li>
                            {% if request|isPatient %}
                            <li><a href="{% url 'appointment:schedule' %}"> &#x270e; Create an appointment</a>
                                {% elif request|isDoctor %}
                            <li><a href="{% url 'appointment:scheduleDoctor' %}"> &#x270e; Create an appointment</a>
                            </li>
                            {% elif request|isNurse %}
                            <li><a href="{% url 'appointment:scheduleNurse' %}">&#x270e; Create an appointment</a></li>
                            {% endif %}
                        </ul>
                    </li>

                    <li class="dropdown" data-item='messages'>

                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false"> Messaging
                            <span class="caret"></span></a>

                        <ul class="dropdown-menu">
                            <li><a href="{% url 'messages:inbox' %}">View your messages</a></li>
                            <li><a href="{% url 'messages:send' %}"> &#x270e; Send a message</a></li>
                            <li><a href="{% url 'messages:outbox' %}">View your sent messages</a></li>
                        </ul>
                    </li>

                    {% endif %}

                    {% if request|isPatient %}
                    <li data-item="prescription"><a href="{% url 'prescription:view' %}">Prescriptions</a></li>

                    {% elif request|isDoctor %}
                    <li class="dropdown" data-item='patients'>

                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false"> Patients
                            <span class="caret"></span></a>

                        <ul class="dropdown-menu">
                            <li><a href="{% url 'patient:patientList' %}">View patient list</a></li>
                            <li><a href="{% url 'patient:admittedPats' %}">View admitted patients</a></li>
                        </ul>
                    </li>

                    <li class="dropdown" data-item='prescription'>

                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false"> Prescriptions
                            <span class="caret"></span></a>

                        <ul class="dropdown-menu">
                            <li><a href="{% url 'prescription:view' %}">View past prescriptions</a></li>
                            <li><a href="{% url 'prescription:create' %}">Write a prescription</a></li>
                        </ul>
                    </li>

                    {% elif request|isNurse %}
                    <li class="dropdown" data-item='patients'>

                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false"> Patients
                            <span class="caret"></span></a>

                        <ul class="dropdown-menu">
                            <li data-item="patients"><a href="{% url 'patient:patientList' %}">View your patients</a>
                            </li>
                            <li><a href="{% url 'patient:admittedPats' %}">View admitted patients</a></li>
                        </ul>
                    </li>
                    <li data-item="prescription"><a href="{% url 'prescription:view' %}">Prescriptions</a></li>
                    {% endif %}

                    {% if request|isAdmin or request|isRoot %}
                    <li data-item='hospital' class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false"> Hospitals <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">Staff</li>
                            <li><a href="{% url 'profile:viewAllPersonnel' %}">View Personnel</a></li>
                            <li><a href="{% url 'register:createDoctor' %}"> Create Doctor </a></li>
                            <li><a href="{% url 'register:createNurse'%}"> Create Nurse</a></li>
                            <li><a href="{% url 'register:createAdmin' %}"> Create Admin</a></li>
                            <li class="dropdown-header">Patients</li>
                            <li><a href="{% url 'patient:patientList' %}">View Patients</a></li>
                            {% if request|isRoot %}
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">Root actions</li>
                            <li><a href="{% url 'hospital:view' %}">Hospitals</a></li>
                            {% endif %}
                        </ul>
                    </li>
                    <li data-item='log' class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false"> System <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'systemLog:log' %}">Log</a></li>
                            <li><a href="{% url 'systemLog:stats' %}">Statistics</a></li>
                        </ul>
                    </li>
                    {% if request|isRoot %}
                    <li data-item="admin"><a href="{% url 'admin:index' %}">Admin Interface</a></li>
                    {% endif %}
                    {% endif %}

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li data-item="profile" class="dropdown">

                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">
                            {{user.first_name}}
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'profile:viewProfile' %}">View profile</a></li>
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">User actions</li>
                            <li><a href="{% url 'profile:userLogout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </nav>

    <!-- Feature custom content for whatever page you're on -->
    {% block content %}
    {% endblock %}

    <!-- If the user is not logged in -->
    {% else %}

    <!-- Create a blank Navbar -->
    <nav class="navbar navbar-default navbar-fixed-top" id='login-nav'>
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'base:landing' %}">HealthNet</a>
            </div>
            <!-- <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li data-item="home"><a href="{% url 'base:landing' %}">Return to homepage</a></li>
                </ul>
            </div> -->
        </div>
    </nav>

    <!-- If the user is trying to login -->
    {% if loginAttempt %}
    {% block loginForm %}
    {% endblock loginForm %}

    <!-- If the user is trying to register -->
    {% elif registerAttempt %}
    {% block register %}
    {% endblock register %}
    <!-- If the user is trying to logout -->
    {% elif logoutAttempt %}
    {% block logout %}
    {% endblock logout %}
    {% endif %}

    {% endif %}

    <!-- Load the scripts at the end of the file to increase performance -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Block for loading custom scripts, including calendar -->
    {% block scripts %}
    {% endblock scripts %}

    </body>
    </html>
</DOCTYPE>

src/healthnet/base/templates/base/test.html
{% load staticfiles %}

<DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>
            HealthNet - Appointments
        </title>

        <!-- Universal styling -->
        <link type='text/css' href="{% static 'css/bootstrap.css' %}" rel='stylesheet'>
        <link type='text/css' href="{% static 'css/navbar.css' %}" rel='stylesheet'>
        <link type='text/css' href="{% static 'css/utilities.css' %}" rel='stylesheet'>

        <!-- Page specific styling -->
        <link type='text/css' href="{% static 'css/fullcalendar.css' %}" rel='stylesheet'/>
        <link type='text/css' href="{% static 'css/appointment.css' %}" rel='stylesheet'/>

        <!-- Font styling -->
        <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    </head>


    <body>

            <div id="appointmentCalendar"></div>


    <!-- Load the scripts at the end of the file to increase performance -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/fullcalendar.min.js' %}"></script>
    <script type="text/javascript">
            $(document).ready(function() {

                // page is now ready, initialize the calendar...

                $('#appointmentCalendar').fullCalendar({
                    // put your options and callbacks here
                    //height: 450
                    events:
                            {{ cal }}

                })

            });


    </script>
    </body>
    </html>
</DOCTYPE>