src/healthnet/base/urls.py
from django.conf.urls import url

from . import views

"""
    @description: The Landing Page for the HealthNet Application
"""
urlpatterns = [
    url(r'^$', views.redirectLanding),
    url(r'^home/$', views.landingPage, name='landing'),
]

src/healthnet/healthnet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^healthnet/', include([     # Branches everything off of "healthnet/"
            # Site landing page
        url(r'', include('base.urls', namespace='base')),
            # Viewing the system log
        url(r'^system/log/', include('viewLog.urls', namespace='systemLog')),
            # Register users
        url(r'^register/', include('register.urls', namespace='register')),
            # Profile Functionality
        url(r'^profile/', include('userprofile.urls', namespace='profile')),
            # Appointment Functionality
        url(r'^apt/', include('appointment.urls', namespace='appointment')),
            # Medical History functionality
        url(r'^medical/', include('medicalHistory.urls',namespace='medical')),
            # Hospital Functionality
        url(r'^hospital/', include('hospital.urls', namespace='hospital')),
            # Admin Interface
        url(r'^admin/', include(admin.site.urls)),
        url(r'^prescription/', include('prescription.urls', namespace='prescription')),
            # Patient list functionality
        url(r'^patients/', include('patient.urls', namespace='patient')),
        url(r'^messages/', include('messaging.urls', namespace='messages')),
        url(r'^results/', include('testResults.urls', namespace='results')),
    ])),
    url(r'^$', views.redirectLanding),
    url(r'^admin/$', views.redirectAdmin),
]
if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, })]

src/healthnet/testResults/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^upload/$',views.uploadResults,name='uploadTest'),
    url(r'^viewResults/$',views.viewAllResults,name='viewTestResults'),
    url(r'^update/(?P<pk>[0-9]+)/$',views.updateResults,name='updateTest'),
    url(r'^comments/(?P<pk>[0-9]+)/$',views.viewComments,name='viewComments'),
]

src/healthnet/testResults/models.py
from django.db import models

# Create your models here.

src/healthnet/testResults/forms.py
from django import forms
from base.models import testResults, Patient
from django.contrib.auth.models import User

CHOICES = ((True,'Yes'),(False,'No'))
class TestUploadForm(forms.ModelForm):
    results = forms.FileField(widget=forms.ClearableFileInput(),label='Upload A File')
    comments = forms.CharField(widget=forms.Textarea(),label="Additional Comments",required=False)
    patient = forms.ModelChoiceField(Patient.objects.all(),empty_label='Choose A Patient',label="Patients")
    published = forms.TypedChoiceField(choices=CHOICES,label="Release for view?",widget=forms.RadioSelect)
    class Meta:
        model = testResults
        fields = ['results','comments','patient','published']
        exclude = ('doctor',)


class UpdateTestResultForm(forms.ModelForm):
    results = forms.FileField()
    comments = forms.CharField(widget=forms.Textarea(),label="Additional Comments",required=False)
    patient = forms.ModelChoiceField(Patient.objects.all(),empty_label='Choose A Patient',label="Patients")
    published = forms.TypedChoiceField(choices=CHOICES,label="Release for view?",widget=forms.RadioSelect)
    class Meta:
        model = testResults
        fields = ['results','comments','patient','published']
        exclude = ('doctor',)

src/healthnet/testResults/views.py
from django.shortcuts import render
from .forms import *
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from base.models import Doctor, Patient, Person, testResults, Logger
from django.shortcuts import render, get_object_or_404
from base.views import group_required
# Create your views here.
@login_required
@group_required('Doctor')
def uploadResults( request ):
    currUser = request.user
    currPerson = Person.objects.get(user=currUser)
    currDoctor = Doctor.objects.get(personID=currPerson)

    if request.method == 'POST':
        form = TestUploadForm(request.POST,request.FILES)

        if form.is_valid():

            # resultFile = form.cleaned_data['results']
            # patient = form.cleaned_data['patient']
            # comments = form.cleaned_data['comments']
            # testResults.objects.create(results=resultFile,doctor=currDoctor,
            #                            patient=patient,comments=comments)

            testResult = form.save(commit=False)
            #testResults.objects.create(results=form.results,comments=form.comments)
            testResult.doctor = currDoctor
            testResult.save()
            Logger.createLog('Created',currUser,testResult,currDoctor.hospitalID)
            return HttpResponseRedirect(reverse("results:viewTestResults"))
        else:
            print(form.errors)
    else:
        form = TestUploadForm()
    context = {'doctor':currDoctor,'form':form}

    return render( request,'testResults/uploadResults.html',context )

@login_required
@group_required('Doctor','Patient')
def viewAllResults( request ):
    allResults = testResults.objects.all()
    currUser = request.user
    currPerson = Person.objects.get(user=currUser)
    if Patient.objects.filter(personID=currPerson).exists():
        currPatient = Patient.objects.get(personID=currPerson)

        # Grab the appts
        results = testResults.objects.all().filter(patient=currPatient)
        publishedResults = list( filter ( lambda x: x.published == True,results ) )
        context = {'results':publishedResults}
        return render(request, 'testResults/patientResults.html', context)

    elif Doctor.objects.filter(personID=currPerson).exists():
        currDoctor = Doctor.objects.get(personID=currPerson)

        # Grab the appts
        results = testResults.objects.filter(doctor=currDoctor)

        context = {'results':results}
        return render(request, 'testResults/results.html', context)

@login_required
@group_required('Patient')
def viewComments(request,pk):
    resultModel = get_object_or_404(testResults,id=pk)
    context = {'comments':resultModel.comments}
    return render(request,'testResults/viewComments.html',context)

@login_required
@group_required('Doctor')
def updateResults(request,pk):
    resultModel = get_object_or_404(testResults,id=pk)

    if request.method == 'POST':
        form = UpdateTestResultForm(request.POST,request.FILES,instance=resultModel)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("results:viewTestResults"))
        else:
            print(form.errors)
    else:
        form = UpdateTestResultForm(instance=resultModel)
    context = {'form':form,'id':resultModel.id}
    return render(request,'testResults/update.html',context)

src/healthnet/testResults/templates/testResults/patientResults.html
{% extends "base/navbar.html" %}
{% load staticfiles %}
{% load static %}
{% load app_filters %}

{% block content %}
{% if results|length == 0 %}
    <h1>There are no test results for view. Please try again later.</h1>
{% else %}
<div class="centerBox">
    <table id="testTable" class='table table-striped'>
        <th>Patient:</th>
        <th>File:</th>
        <th>Comments:</th>
        {% for res in results %}
        <tr>

            <td>{{ res.patient }}</td>
            <td> <a href="{{MEDIA_URL}}{{res.results}}">Test File</a></td>
            <td><a href="{%url 'results:viewComments' res.id%}">Comments</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endif %}

{% endblock %}

src/healthnet/testResults/templates/testResults/results.html
{% extends "base/navbar.html" %}
{% load staticfiles %}
{% load static %}
{% load app_filters %}

{% block content %}
<div class='center-container'>
    {% if request|isDoctor or request|isAdmin %}
        <a class='confirm' href="{%url 'results:uploadTest' %}">Upload a Test</a>
    {% endif %}
</div>
<div class="centerBox">
    <table id="testTable" class='table table-striped'>
        <th>Patient:</th>
        <th>File:</th>
        <th>Published?</th>
        {% for res in results %}
        <tr>

            <td>{{ res.patient }}</td>
            <td> <a href="{{MEDIA_URL}}{{res.results}}">Test File</a></td>
            <td> {% if res.published %} YES {%else%} NO {%endif%}</td>
            <td>
                <a class='confirm' href="{% url 'results:updateTest' res.id%}"> &#x270e; Edit</a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

src/healthnet/testResults/templates/testResults/update.html
{% extends "base/navbar.html" %}
{% load app_filters %}

{% block content %}

<title>Upload test Results</title>

<form id="UploadResults" class='form-center' method="post" action="{% url 'results:updateTest' id%}"enctype="multipart/form-data">
    {%csrf_token%}
    {{ form.errors }}
    {#{{ form.as_p}}#}
    <tr>
        <th>
            <label for="id_results">Results:</label>
        </th>
        <td>
            <br>
            <p>Current File: <a href="/media/files/Lab_8.pdf">Test file</a></p>
        <br />
            <p>Change: <input id="id_results" name="results" type="file" /></p>
        </td>
    </tr>

    <label for="id_comments">Additional Comments:</label>
    <br>
    {{ form.comments }}
    <br>
    <label for="id_patient">Patient:</label>
    {{ form.patient }}
    <br>
    <label for="id_published_0">Release for view?</label>
    {{ form.published }}
    <input class='confirm left' type="submit" name="submit" value="Update"/>
    <a class='delete' href="{% url 'results:viewTestResults' %}">Cancel</a>
</form>

{% endblock %}

src/healthnet/testResults/templates/testResults/uploadResults.html
{% extends "base/navbar.html" %}
{% load app_filters %}

{% block content %}

<title>Upload test Results</title>

<form id="UploadResults" class='form-center' method="post" action="{% url 'results:uploadTest' %}"enctype="multipart/form-data">
    {%csrf_token%}
    {{ form.errors }}
    {{ form.as_p}}
    <input class='confirm left' type="submit" name="submit" value="Upload"/>
    <a class='delete' href="{% url 'results:viewTestResults' %}">Cancel</a>
</form>

{% endblock %}

src/healthnet/testResults/templates/testResults/viewComments.html
{% extends "base/navbar.html" %}
{% load staticfiles %}
{% load static %}
{% load app_filters %}

{% block content %}

{% if comments == "" %}
    <h1>No comments have been added for this test. Please try again later.</h1>
{% else %}
<h1>Comments for your test results.</h1>
<label for="id_comments">Comments about test results:</label>
<p>&nbsp;&nbsp;&nbsp;&nbsp;{{ comments }}</p>
<br>
<br>
<p>Return to your <a href="{% url 'results:viewTestResults' %}">list of test results.</a></p>
{%endif%}
{% endblock %}