src/healthnet/base/urls.py
from django.conf.urls import url

from . import views

"""
    @description: The Landing Page for the HealthNet Application
"""
urlpatterns = [
    url(r'^$', views.redirectLanding),
    url(r'^home/$', views.landingPage, name='landing'),
]

src/healthnet/healthnet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^healthnet/', include([     # Branches everything off of "healthnet/"
            # Site landing page
        url(r'', include('base.urls', namespace='base')),
            # Viewing the system log
        url(r'^system/log/', include('viewLog.urls', namespace='systemLog')),
            # Register users
        url(r'^register/', include('register.urls', namespace='register')),
            # Profile Functionality
        url(r'^profile/', include('userprofile.urls', namespace='profile')),
            # Appointment Functionality
        url(r'^apt/', include('appointment.urls', namespace='appointment')),
            # Medical History functionality
        url(r'^medical/', include('medicalHistory.urls',namespace='medical')),
            # Hospital Functionality
        url(r'^hospital/', include('hospital.urls', namespace='hospital')),
            # Admin Interface
        url(r'^admin/', include(admin.site.urls)),
        url(r'^prescription/', include('prescription.urls', namespace='prescription')),
            # Patient list functionality
        url(r'^patients/', include('patient.urls', namespace='patient')),
        url(r'^messages/', include('messaging.urls', namespace='messages')),
        url(r'^results/', include('testResults.urls', namespace='results')),
    ])),
    url(r'^$', views.redirectLanding),
    url(r'^admin/$', views.redirectAdmin),
]
if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, })]

src/healthnet/hospital/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.hospitalRedirect),
    url(r'^create/$', views.createHospital, name='create'),
    url(r'^view/$', views.viewHospitals, name='view'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.updateHospital.as_view(), name='update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.deleteHospital, name='delete'),
]

src/healthnet/medicalHistory/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.createHistory, name='create'),
    url(r'^view/(?P<pk>[0-9]+)/$', views.viewHistory, name='history'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.update, name='update'),
    url(r'^error/$', views.viewHistory, name='error'),
]

src/healthnet/messaging/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^compose/$', views.compose, name='send'),
    url(r'^compose/(?P<recipient>[0-9]+)/$', views.compose, name='send'), # Send a message to a specific person
    url(r'^inbox/$', views.inbox, name='inbox'),
    url(r'^outbox/$', views.outbox, name='outbox'),
    url(r'^view/(?P<message_id>[\d]+)/$', views.view, name='view'),
    url(r'^delete/(?P<message_id>[\d]+)/$', views.delete, name='delete'),
    url(r'^reply/(?P<message_id>[\d]+)/$', views.reply, name='reply'),
]
    

src/healthnet/register/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^admin/$', views.createAdmin, name='createAdmin'),
    url(r'^patient/$', views.createPatient, name='createPatient'),
    url(r'^doctor/$', views.createDoctor, name='createDoctor'),
    url(r'^nurse/$', views.createNurse, name='createNurse'),
]

src/healthnet/userprofile/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login/$', views.userLogin, name='userLogin'),
    url(r'^logout/$', views.userLogout, name='userLogout'),

    url(r'^view/$', views.viewProfile, name='viewProfile'),
    url(r'^Adminview/(?P<pk>[0-9]+)/$$', views.AdminView, name='AdminView'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.updateProf, name='userUpdate'),
    url(r'^update/Doc(?P<pk>[0-9]+)/$', views.updateDoctor, name='doctorUpdate'),
    url(r'^update/Nur(?P<pk>[0-9]+)/$', views.updateNurse, name='nurseUpdate'),
    url(r'^update/Adm(?P<pk>[0-9]+)/$', views.updateAdmin, name='adminUpdate'),
    url(r'^update/Root(?P<pk>[0-9]+)/$', views.updateRoot, name='rootUpdate'),

    url(r'^personnel/$', views.viewAllPersonnel, name='viewAllPersonnel'),

    url(r'^delete/Doc(?P<pk>[0-9]+)/$', views.deleteDoc, name='deleteDoc'),
    url(r'^delete/Nur(?P<pk>[0-9]+)/$', views.deleteNurse, name='deleteNurse'),
    url(r'^delete/Adm(?P<pk>[0-9]+)/$', views.deleteAdmin, name='deleteAdmin'),

    url(r'^move/Nur(?P<pk>[0-9]+)/$', views.moveNurse, name='moveNurse'),
    url(r'^move/Doc(?P<pk>[0-9]+)/$', views.moveDoctor, name='moveDoctor'),

    url(r'^preferred/(?P<pk>[0-9]+)/$',views.getPreferredHospitals, name='preferredHospitals'),
    url(r'^updatePreferred/(?P<pk>[0-9]+)/$',views.updatePreferredHospitals,name='updatePreferredHospitals')
]

src/healthnet/userprofile/models.py
from django.db import models

# Create your models here.

src/healthnet/userprofile/views.py
"""
    Application: HealthNet
    File: /patientUpdate/views.py
    Authors:
        - Nathan Stevens
        - Phillip Bedward
        - Daniel Herzig
        - George Herde
        - Samuel Launt

    Description:
        - This file contains all the forms for updating a Patient's profile
"""
import logging
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from datetime import datetime
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, render_to_response
from django.apps import apps
from django.core.urlresolvers import reverse
from django.template import RequestContext
from base.models import Doctor, Nurse, Admin, Person, Patient, Root, Insurance, Address, Logger, Appointment, Message, inbox_count_for
# from base.models import *
from base.views import group_required
from .forms import *


Cperson = apps.get_model("base", "Person")
doctor = apps.get_model("base", "Doctor")
nurse_model = apps.get_model("base", "Nurse")
admin = apps.get_model("base", "Admin")
root = apps.get_model('base', 'Root')
Cpatient = apps.get_model("base", "Patient")
Caddress = apps.get_model("base", "Address")
Cinsurance = apps.get_model("base", "Insurance")
Cemergencycontact = apps.get_model("base", "EmergencyContact")


# Create your views here.
def userLogin(request):
    """
    @function: userLogin
    @description: This controller definition controls the functionality for
                  when a user logs in.
    """
    # The user is attempting to login, so create a context variable
    loginAttempt = True

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        # We use request.POST.get('<variable>') as opposed to request.POST['<variable>'],
        # because the request.POST.get('<variable>') returns None, if the value does not exist,
        # while the request.POST['<variable>'] will raise key error exception
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)

                # Logger.createLog('Logged in',user.personID)
                return HttpResponseRedirect(reverse('profile:userLogin'))
            else:
                disabledAccount = True
                context = {'disabledAccount': disabledAccount,
                           'loginAttempt': loginAttempt}
                # An inactive account was used - no logging in!
                return render(request, 'userprofile/login.html', context)
        else:
            failedLogin = True
            loginAttempt = True
            # Redefine the context variable to include the failedLogin variable
            context = {'failedLogin': failedLogin,
                       'loginAttempt': loginAttempt}
            # Bad login details were provided. So we can't log the user in.
            return render(request, "userprofile/login.html", context)

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        currentUser = request.user.id
        personBool = Person.objects.filter(user=currentUser).exists()
        if personBool:
          person_model = Person.objects.get(user=currentUser)

          if Doctor.objects.filter(personID=person_model).exists():
            doctor_model = Doctor.objects.get(personID=person_model.id)
            appointments = Appointment.objects.all().filter(doctorID=doctor_model, aptDate__gte=datetime.today())[:3]
            messageCount = inbox_count_for(currentUser)
            messages = Message.objects.inbox_for(person_model)[:3]
            context = {'appointments': appointments, 'loginAttempt': loginAttempt, 'messageCount': messageCount,
            'messages': messages}
            return render(request, 'userprofile/login.html', context)

          elif Patient.objects.filter(personID=person_model).exists():
            patient_model = Patient.objects.get(personID=person_model.id)     
            appointments = Appointment.objects.all().filter(patientID=patient_model, aptDate__gte=datetime.today())[:3]
            messageCount = inbox_count_for(currentUser)
            messages = Message.objects.inbox_for(person_model)[:3]
            context = {'appointments': appointments, 'loginAttempt': loginAttempt, 'messageCount': messageCount,
            'messages': messages}
            return render(request, 'userprofile/login.html', context)

          elif Nurse.objects.filter(personID=person_model).exists():
            nurse_model = Nurse.objects.get(personID=person_model.id)
            allAppointments = Appointment.objects.filter(aptDate__gte=datetime.today())
            appointments = []
            for appt in allAppointments:
              if ((appt.doctorID.hospitalID.id == nurse_model.hospitalID.id)):
                appointments.append(appt)
            messageCount = inbox_count_for(currentUser)
            messages = Message.objects.inbox_for(person_model)[:3]
            context = {'appointments': appointments, 'loginAttempt': loginAttempt, 'messageCount': messageCount,
            'messages': messages}
            return render(request, 'userprofile/login.html', context)
          else:
            return render(request, 'userprofile/login.html', {'loginAttempt': loginAttempt})
        else:
            return render(request, 'userprofile/login.html', {'loginAttempt': loginAttempt})




@login_required
def userLogout(request):
    """
    @function: userLogout
    @description: This controller definition controls the functionality for
                  when a user logs out.
    """
    currentUser = request.user
    request.session.items = []
    request.session.modified = True
    logout(request)
    logoutAttempt = True
    return render(request, 'userprofile/logout.html', {'logoutAttempt': logoutAttempt})


@login_required
def viewProfile(request, **kwargs):
    """
    @function: viewProfile
    @description: viewProfile lets the user view their current settings and profile information.
    """
    currentUser = request.user
    user_model = User.objects.get_by_natural_key(currentUser.username)
    # Grab the user information forms
    firstName = user_model.first_name
    lastName = user_model.last_name
    # Add the names together
    fullName = firstName + ' ' + lastName
    email = user_model.email

    # Get the doctor's models
    person_model = Person.objects.get(user=user_model)

    if request.user.groups.filter(name='Patient').exists():
        patientInfo = Cpatient.objects.get(personID=person_model)
        # Grab the person identified with patient
        phoneNumber = patientInfo.personID.phoneNumber
        birthday = patientInfo.personID.birthday

        # Grab the address
        street = patientInfo.addressID.street
        city = patientInfo.addressID.city
        state = patientInfo.addressID.state
        zip = str(patientInfo.addressID.zip)
        # Add all the info together
        addressInfo = street + ' \n' \
                      + city + ' , ' + state + ' ' + zip

        # Grab the insurance info
        policyNumber = patientInfo.insuranceID.policyNumber
        insuranceName = patientInfo.insuranceID.name

        if patientInfo.medicalID == None:
            medicalID = -1
        else:
            medicalID = patientInfo.medicalID.id

        context = {'fullName': fullName,
                   'email': email,
                   'phoneNumber': phoneNumber,
                   'birthday': birthday,
                   'addressInfo': addressInfo,
                   'policyNumber': policyNumber,
                   'insuranceName': insuranceName,
                   'emergencyContact': patientInfo.emergencyContactID,
                   'patientID': person_model.id,
                   'medicalID': medicalID,
                   'patient':Cpatient.objects.get(personID=person_model)}
        return render(request, 'userprofile/profile.html', context)

    elif request.user.groups.filter(name='Doctor').exists():
        doctorInfo = doctor.objects.get(personID=person_model)

        phoneNumber = doctorInfo.personID.phoneNumber
        birthday = doctorInfo.personID.birthday
        # Grab the address
        street = doctorInfo.addressID.street
        city = doctorInfo.addressID.city
        state = doctorInfo.addressID.state
        zip = str(doctorInfo.addressID.zip)
        # Add all the info together
        addressInfo = street + ' \n' \
                      + city + ' , ' + state + ' ' + zip

        hospitalName = doctorInfo.hospitalID.name
        hospitalAddress = doctorInfo.hospitalID.address

        licenseNumber = doctorInfo.licenseNumber
        specialty = doctorInfo.specialty

        context = {'fullName': fullName,
                   'email': email,
                   'phoneNumber': phoneNumber,
                   'birthday': birthday,
                   'addressInfo': addressInfo,
                   'personID': doctorInfo.id,
                   'hospitalName': hospitalName,

src/healthnet/userprofile/templates/userprofile/Adminprofile.html
{% extends "base/navbar.html" %}
{% load app_filters %}

{% block content %}

    <title>HealthNet - View profile</title>

    <h1>View your profile</h1>
    {% if patient %}
    <table class='table table-hover'>
        <tr>
            <th class='table-heading' colspan="2">User information</th>
        </tr>
        <tr>
            <th>User Type</th>
            <td> Patient</td>
        </tr>
        <tr>
            <th>Name</th>
            <td> {{fullName}}</td>
        </tr>
        <tr>
            <th>Email address</th>
            <td> {{email}}</td>
        </tr>
        <tr>
            <th>Phone number</th>
            <td> {{phoneNumber}}</td>
        </tr>
        <tr>
            <th>Birthday</th>
            <td> {{birthday}}</td>
        </tr>
        <tr>
            <th>Address</th>
            <td> {{addressInfo}}</td>
        </tr>
        <tr>
            <th class='table-heading' colspan="2">Insurance information</th>
        </tr>
        <tr>
            <th>Insurance name</th>
            <td> {{insuranceName}}</td>
        </tr>
        <tr>
            <th>Policy number</th>
            <td> {{policyNumber}}</td>
        </tr>
        <tr>
            <th class='table-heading' colspan="2">Emergency Contact information</th>
        </tr>
        <tr>
            <th>Contact name</th>
            <td> {{emergencyContact.firstName}} {{emergencyContact.lastName}}</td>
        </tr>
        <tr>
            <th>Phone number</th>
            <td> {{emergencyContact.emergencyNumber}}</td>
        </tr>
    </table>

    <div class='center-container'>
        <a class="btn btn-primary confirm" href="{% url 'profile:userUpdate' patientID %}" role="button">&#x270e; Edit your
            profile</a>
        {% if medicalID = -1 %}
        <a class="btn btn-primary confirm" href="{% url 'medical:create' %}" role="button">Start Medical History</a>
        {% else %}
        <a class="btn btn-primary confirm" href="{% url 'medical:history' medicalID %}" role="button">Medical History</a>
        {% endif %}
    </div>

    {% elif doctor %}
    <table class='table table-hover'>
        <tr>
            <th class='table-heading' colspan="2">User information</th>
        </tr>
        <tr>
            <th>User Type</th>
            <td> Doctor</td>
        </tr>
        <tr>
            <th>Name</th>
            <td> {{fullName}}</td>
        </tr>
        <tr>
            <th>Email address</th>
            <td> {{email}}</td>
        </tr>
        <tr>
            <th>Phone number</th>
            <td> {{phoneNumber}}</td>
        </tr>
        <tr>
            <th>Birthday</th>
            <td> {{birthday}}</td>
        </tr>
        <tr>
            <th>Address</th>
            <td> {{addressInfo}}</td>
        </tr>
        <tr>
            <th class='table-heading' colspan="2">Professional information</th>
        </tr>
        <tr>
            <th>Specialty</th>
            <td> {{specialty}}</td>
        </tr>
        <tr>
            <th>License Number</th>
            <td> {{licenseNumber}}</td>
        </tr>
        <tr>
            <th class='table-heading' colspan="2">Hospital information</th>
        </tr>
        <tr>
            <th>Name</th>
            <td> {{hospitalName}}</td>
        </tr>
        <tr>
            <th>Address</th>
            <td> {{hospitalAddress}}</td>
        </tr>
    </table>

    <div class='center-container'>
        <a class="btn btn-primary confirm" href="{% url 'profile:doctorUpdate' personID %}" role="button">&#x270e; Edit your
            profile</a>
    </div>

    {% elif nurse %}
    <table class='table table-hover'>
        <tr>
            <th class='table-heading' colspan="2">User information</th>
        </tr>
        <tr>
            <th>User Type</th>
            <td> Nurse</td>
        </tr>
        <tr>
            <th>Name</th>
            <td> {{fullName}}</td>
        </tr>
        <tr>
            <th>Email address</th>
            <td> {{email}}</td>
        </tr>
        <tr>
            <th>Phone number</th>
            <td> {{phoneNumber}}</td>
        </tr>
        <tr>
            <th>Birthday</th>
            <td> {{birthday}}</td>
        </tr>
        <tr>
            <th>Address</th>
            <td> {{addressInfo}}</td>
        </tr>
        <tr>
            <th class='table-heading' colspan="2">Professional information</th>
        </tr>
        <tr>
            <th>Department</th>
            <td> {{department}}</td>
        </tr>
        <tr>
            <th>License Number</th>
            <td> {{licenseNumber}}</td>
        </tr>
        <tr>
            <th class='table-heading' colspan="2">Hospital information</th>
        </tr>
        <tr>
            <th>Name</th>
            <td> {{hospitalName}}</td>
        </tr>
        <tr>
            <th>Address</th>
            <td> {{hospitalAddress}}</td>
        </tr>
    </table>

    <div class='center-container'>
        <a class="btn btn-primary confirm" href="{% url 'profile:nurseUpdate' personID %}" role="button">&#x270e; Edit your
            profile</a>
    </div>

    {% elif admin %}
    <table class='table table-hover'>
        <tr>
            <th class='table-heading' colspan="2">User information</th>
        </tr>
        <tr>
            <th>User Type</th>
            <td> Hospital Admin</td>
        </tr>
        <tr>
            <th>Name</th>
            <td> {{fullName}}</td>
        </tr>
        <tr>
            <th>Email address</th>
            <td> {{email}}</td>
        </tr>
        <tr>
            <th>Phone number</th>
            <td> {{phoneNumber}}</td>
        </tr>
        <tr>
            <th>Birthday</th>
            <td> {{birthday}}</td>
        </tr>
        <tr>
            <th>Address</th>
            <td> {{addressInfo}}</td>
        </tr>
        <tr>
            <th class='table-heading' colspan="2">Hospital information</th>
        </tr>
        <tr>
            <th>Name</th>
            <td> {{hospitalName}}</td>
        </tr>
        <tr>
            <th>Address</th>
            <td> {{hospitalAddress}}</td>
        </tr>
    </table>

    <div class='center-container'>
        <a class="btn btn-primary confirm" href="{% url 'profile:adminUpdate' personID %}" role="button">&#x270e; Edit your
            profile</a>
    </div>

    {% elif root %}
    <table class='table table-hover'>
        <tr>
            <th class='table-heading' colspan="2">User information</th>
        </tr>
        <tr>
            <th>User Type</th>
            <td> System Root</td>
        </tr>
        <tr>
            <th>Name</th>
            <td> {{fullName}}</td>
        </tr>
        <tr>
            <th>Email address</th>
            <td> {{email}}</td>
        </tr>
        <tr>
            <th>Phone number</th>
            <td> {{phoneNumber}}</td>
        </tr>
        <tr>
            <th>Birthday</th>
            <td> {{birthday}}</td>
        </tr>
        <tr>
            <th>Address</th>
            <td> {{addressInfo}}</td>
        </tr>
    </table>

    <div class='center-container'>
        <a class="btn btn-primary confirm" href="{% url 'profile:userUpdate' personID %}" role="button">&#x270e; Edit your
            profile</a>
    </div>
    {% endif %}

{% endblock content %}

src/healthnet/userprofile/templates/userprofile/login.html
{% extends "base/navbar.html" %}
{% load app_filters %}

{% block content %}
<!-- Set the title of the page to be Home --> 
<title> HealthNet - Profile</title>
<div class="container">

    <!-- Main component for a primary marketing message or call to action -->
    <div class="jumbotron">
        <h1>Welcome to HealthNet, {{ user.first_name }}!</h1>
    </div>

    {% if request|isDoctor or request|isNurse or request|isPatient %}
    <div class="container">
	    <div class="row">
	      <div class="col-sm-6">
	        <div class="panel panel-primary">
	          <div class="panel-heading">
	            <h2 class="panel-title helpText">Here are your upcoming appointments:</h2>
	          </div>
	          <div class="panel-body">
	          {% if appointments %}
	          	{% for app in appointments %}
	          		<h4><li>Appointment with <b>{{app.doctorID}}</b> at <b>{{app.aptTime}}</b> on {{app.aptDate}}</li></h4>
	          	{% endfor %}
	          {% else %}
	          <h4>No upcoming appointments!</h4>
	          {% endif %}
	          </div>
	          <div class='panel-footer'>
	          	<h2 class='panel-title helpText'><a class='helpText' href="{% url 'appointment:view' %}"> &#9654; Click here to view your appointments. </a></h2>
	          </div>
	        </div>
	      </div>

	      <div class="col-sm-6">
		    {% if messageCount >= 1 %}
	        <div class="panel panel-danger">
	        {% else %}
	        <div class="panel panel-primary">
	        {% endif %}
	          <div class="panel-heading">
	            <h2 class="panel-title helpText">You have {{messageCount}} new messages:</h2>
	          </div>
	          <div class="panel-body">
	          {% if messages %}
	          	{% for m in messages %}
	          		<h4><li>Message from <b>{{m.sender}}</b> sent at <b>{{m.sent_at}}</b></li></h4>
	          	{% endfor %}
	          {% else %}
	          <h4>No new messages!</h4>
	          {% endif %}
	          </div>
	          <div class='panel-footer'>
	          	<h2 class='panel-title helpText'><a class='helpText' href="{% url 'messages:inbox' %}"> &#9654; Click here to view your inbox. </a></h2>
	          </div>
	        </div>
	      </div>
	    </div>
	 </div>
    {% endif %}

</div>

{% endblock content %}

{% block loginForm %}
	<!-- If the account is disabled -->
	{% if disabledAccount %}
		<h3>The account you entered has been disabled. Please click
			<a href="{% url 'register:createPatient' %}">here</a>
		to re-register.</h3>
	<!-- Otherwise show the forms-->
	{% else %}

    <h1 id="login-info">Login to HealthNet</h1>

	    <div id='form-container'>
	        <!-- Check if the login attempt has failed-->
	        {% if failedLogin %}
	            <h3>The username or password entered was incorrect. Please try again.</h3>
	        {% endif %}

	        <!-- Display the form-->
	        <form id="login_form" class='form-center' method="post" action="{% url 'profile:userLogin' %}">
	            {% csrf_token %}
	            <div class='form-group'>
	                <label for='username'> Username </label>
	                <input class="form-control" id="username" type="text" name="username" value="" size="50"/>
	            </div>

	            <div class='form-group'>
	                <label for='password'> Password </label>
	                <input class="form-control" id="password" type="password" name="password" value="" size="50"/>
	            </div>

	            <input class="btn btn-default confirm" type="submit" name="submit" value="Login"/>
	        </form>
	    </div>

	    <h3 id='header'>
	        <a href="{% url 'register:createPatient' %}">Are you not registered with HealthNet yet?</a>
	    </h3>
	{% endif %}

{% endblock loginForm %}

{% block scripts %}
<script type="text/javascript">
	$(document).ready(function() {
		// Add the active class
		$('a[data-item="home"]').addClass("activeHome");
	});
</script> 
{% endblock scripts %}

src/healthnet/userprofile/templates/userprofile/updateAdmin.html
{% extends "base/navbar.html" %}
{% load app_filters %}

{% block content %}

    <title>HealthNet - Profile Update</title>

    <h1>Update Admin Profile</h1>

    <div id="form-container">
    <form id="user_form" class='form-center' method="post" action="{% url 'profile:adminUpdate' admID %}" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- Display each form. The as_p method wraps each element in a paragraph
             (<p>) element. This ensures each element appears on a new line,
             making everything look neater. -->
        {{ user_form.as_p }}
        {{ personForm.as_p }}

        <!-- Provide a button to click to submit the form. -->
        <input class='confirm right' type="submit" name="submit" value="Update"/>
        {% if request|currUser:user %}
        <a class='delete' href="{% url 'profile:viewProfile' %}">Return to profile</a>
        {% else%}
        <a class='neutral' href="{% url 'profile:viewAllPersonnel' %}">Cancel</a>
        {% endif %}
    </form>
    </div>
    <br><br>
{% endblock content %}

{% block scripts %}

    <script type="text/javascript">
        $(document).ready(function() {
            // Add the active class
            $('li[data-item="hospital"]').addClass("active");
        });
    </script> 

{% endblock scripts %}

src/healthnet/userprofile/templates/userprofile/updateDoctor.html
{% extends "base/navbar.html" %}
{% load app_filters %}

{% block content %}

    <title>HealthNet - Profile Update</title>

    <h1>Update Doctor Profile</h1>

    <div id="form-container">
    <form id="user_form" class='form-center' method="post" action="{% url 'profile:doctorUpdate' docID %}" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- Display each form. The as_p method wraps each element in a paragraph
             (<p>) element. This ensures each element appears on a new line,
             making everything look neater. -->
        {{ user_form.as_p }}
        {{ personForm.as_p }}
        {{ employeeUpdate.as_p }}
        <!--{{ addressForm.as_p }}-->

        <!-- Provide a button to click to submit the form. -->
        <input class='confirm right' type="submit" name="submit" value="Update"/>
        {% if request|currUser:user %}
        <a class='delete' href="{% url 'profile:viewProfile' %}">Return to profile</a>
        {% else%}
        <a class='neutral' href="{% url 'profile:viewAllPersonnel' %}">Cancel</a>
        {% endif %}

    </form>
    </div>
    <br><br>
{% endblock content %}

{% block scripts %}

    <script type="text/javascript">
        $(document).ready(function() {
            // Add the active class
            $('li[data-item="hospital"]').addClass("active");
        });
    </script> 

{% endblock scripts %}

src/healthnet/userprofile/templates/userprofile/updatePreferredHospital.html
{% extends "base/navbar.html" %}

{% block content %}
    <!-- Set the title of the page to be what is on the page -->
    <title>HealthNet - Preferred Hospitals</title>

    <div id='form-container'>
    <form id="Update Preferred Hospitals" method="post" action="{% url 'profile:updatePreferredHospitals' patient.id %}">
        {% csrf_token %}
        <h3>What hospital would you prefer to visit? </h3>
            {{ form.as_p }}
            <a class='neutral' href="{% url 'profile:viewProfile' %}">Cancel</a>
            <input class='confirm' type="submit" name='submit' value="Update hospitals"/>
        </form>
    </div>

{% endblock content %}