src/healthnet/appointment/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.redirectAppointment),
    url(r'^view/$', views.viewAppointment, name='view'),

    url(r'^schedule/$', views.scheduleAppointment, name='schedule'),

    url(r'^doccreate/$', views.scheduleDoctor, name='scheduleDoctor'),
    url(r'^doccreate/(?P<patient>[0-9]+)/$', views.scheduleDoctor, name='scheduleDoctor'), # Pass in a patient

    url(r'^nurcreate/$', views.scheduleNurse, name='scheduleNurse'),
    url(r'^nurcreate/(?P<patient>[0-9]+)/$', views.scheduleNurse, name='scheduleNurse'), # Pass in a patient


    url(r'^update/(?P<pk>[0-9]+)/$', views.updateAppointment, name='update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.deleteAppointment, name='delete'),
]
    

src/healthnet/base/urls.py
from django.conf.urls import url

from . import views

"""
    @description: The Landing Page for the HealthNet Application
"""
urlpatterns = [
    url(r'^$', views.redirectLanding),
    url(r'^home/$', views.landingPage, name='landing'),
]

src/healthnet/healthnet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^healthnet/', include([     # Branches everything off of "healthnet/"
            # Site landing page
        url(r'', include('base.urls', namespace='base')),
            # Viewing the system log
        url(r'^system/log/', include('viewLog.urls', namespace='systemLog')),
            # Register users
        url(r'^register/', include('register.urls', namespace='register')),
            # Profile Functionality
        url(r'^profile/', include('userprofile.urls', namespace='profile')),
            # Appointment Functionality
        url(r'^apt/', include('appointment.urls', namespace='appointment')),
            # Medical History functionality
        url(r'^medical/', include('medicalHistory.urls',namespace='medical')),
            # Hospital Functionality
        url(r'^hospital/', include('hospital.urls', namespace='hospital')),
            # Admin Interface
        url(r'^admin/', include(admin.site.urls)),
        url(r'^prescription/', include('prescription.urls', namespace='prescription')),
            # Patient list functionality
        url(r'^patients/', include('patient.urls', namespace='patient')),
        url(r'^messages/', include('messaging.urls', namespace='messages')),
        url(r'^results/', include('testResults.urls', namespace='results')),
    ])),
    url(r'^$', views.redirectLanding),
    url(r'^admin/$', views.redirectAdmin),
]
if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, })]

src/healthnet/hospital/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.hospitalRedirect),
    url(r'^create/$', views.createHospital, name='create'),
    url(r'^view/$', views.viewHospitals, name='view'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.updateHospital.as_view(), name='update'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.deleteHospital, name='delete'),
]

src/healthnet/medicalHistory/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.createHistory, name='create'),
    url(r'^view/(?P<pk>[0-9]+)/$', views.viewHistory, name='history'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.update, name='update'),
    url(r'^error/$', views.viewHistory, name='error'),
]

src/healthnet/messaging/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^compose/$', views.compose, name='send'),
    url(r'^compose/(?P<recipient>[0-9]+)/$', views.compose, name='send'), # Send a message to a specific person
    url(r'^inbox/$', views.inbox, name='inbox'),
    url(r'^outbox/$', views.outbox, name='outbox'),
    url(r'^view/(?P<message_id>[\d]+)/$', views.view, name='view'),
    url(r'^delete/(?P<message_id>[\d]+)/$', views.delete, name='delete'),
    url(r'^reply/(?P<message_id>[\d]+)/$', views.reply, name='reply'),
]
    

src/healthnet/patient/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^patientList/$', views.patientList, name='patientList'),
    url(r'^admit/(?P<pk>[0-9]+)/$',views.admitPatient, name='admitPatient'),
    url(r'^patientInfo/(?P<pk>[0-9]+)/$', views.viewPatientDetails, name='patientDetails'),
    url(r'^admitted/$', views.admittedPatients, name='admittedPats'),
    url(r'^discharge/(?P<pk>[0-9]+)/$', views.dischargePatient, name='discharge'),
    url(r'^transferSuccess/([0-9]+)/$', views.transferPatient, name='transferPatient'),
    url(r'^transferFailed/([0-9]+)/$', views.transferFailed, name='cannotTransfer'),
]

src/healthnet/patient/models.py
from django.db import models

# Create your models here.

src/healthnet/patient/forms.py
"""
    Application: HealthNet
    File: /patient/forms.py
    Authors:
        - Nathan Stevens
        - Philip Bedward
        - Daniel Herzig
        - George Herde
        - Samuel Launt

    Description:
        - This file contains all view controller information
"""
from base.models import ExtendedStay
from django.apps import apps
from django import forms
from django.contrib.auth.models import User
from django.forms.extras.widgets import SelectDateWidget
from django.forms.widgets import NumberInput

address = apps.get_model('base', 'Address')
person = apps.get_model('base', 'Person')
insurance = apps.get_model('base', 'Insurance')
doctor = apps.get_model('base', 'Doctor')
nurse = apps.get_model('base', 'Nurse')
admin = apps.get_model('base', 'Admin')


# Custom forms for the PatientRegistration
class UserForm(forms.ModelForm):
    """
    @class: UserForm
    @description: This form is where the User information is updated
    """
    first_name = forms.CharField(required=True, label='First Name:')
    last_name = forms.CharField(required=True, label='Last Name:')
    email = forms.EmailField(required=True, label='Email:')
    username = forms.CharField(required=True, label='Username:',
                               help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class PersonRegistrationForm(forms.ModelForm):
    """
    @class: PersonRegistrationForm
    @description: This form is where the Person specific information is entered
    """
    birthday = forms.DateField(widget=SelectDateWidget(years={1950, 1951, 1952, 1953, 1954, 1955, 1956,
                                                              1957, 1958, 1959, 1960, 1961, 1962, 1963,
                                                              1964, 1965, 1966, 1967, 1968, 1969, 1970,
                                                              1971, 1972, 1973, 1974, 1975, 1976, 1977,
                                                              1978, 1979, 1980, 1981, 1982, 1983, 1984,
                                                              1985, 1986, 1987, 1988, 1989, 1990, 1991,
                                                              1992, 1993, 1994, 1995, 1996, 1997, 1998,
                                                              1999, 2000, 2001, 2002, 2003, 2004, 2005,
                                                              2006, 2007, 2008, 2009, 2010, 2011, 2012,
                                                              2013, 2014, 2015}),
                               label='Birthday:')
    # ssn = forms.IntegerField(widget=NumberInput, label='SSN:')
    # phoneNumber = USPhoneNumberField()

    class Meta:
        model = apps.get_model('base', 'Person')
        fields = ('birthday', 'phoneNumber')
        exclude = ('ssn',)


class InsuranceForm(forms.ModelForm):
    """
    @class: InsuranceForm
    @description: This form is where the Insurance information is supplied
    """
    name = forms.CharField(label='Name:')
    policyNumber = forms.IntegerField(label='Policy Number:')

    class Meta:
        model = apps.get_model('base', 'Insurance')
        fields = ('name', 'policyNumber')
        exclude = ('addressID',)


class AddressForm(forms.ModelForm):
    """
    @class: AddressForm
    @description: This form is where the Address information is provided
    """
    # zip =  USZipCodeField()
    # state = USStateField()
    #
    class Meta:
        model = apps.get_model('base', 'Address')
        fields = ('street', 'zip', 'city', 'state')


class EmergencyContactForm(forms.ModelForm):
    """
    @class: EmergencyContactForm
    @description: This form is where the Emergency Contact information is entered
    """
    firstName = forms.CharField(required=True, label='First Name:')
    lastName = forms.CharField(required=True, label='Last Name:')
    # emergencyNumber = USPhoneNumberField()


    class Meta:
        model = apps.get_model('base', 'EmergencyContact')
        fields = ('firstName', 'lastName', 'emergencyNumber')
        exclude = ('personID',)


class AdminForm(forms.ModelForm):
    hospital = forms.ModelChoiceField(queryset=admin.objects.all(), empty_label='Choose A Hospital')

    class Meta:
        model = admin
        fields = ('hospital',)


class DeleteDoctor(forms.ModelForm):
    class Meta:
        model = doctor
        fields = []


class DeleteNurse(forms.ModelForm):
    class Meta:
        model = nurse
        fields = []


class DeleteAdmin(forms.ModelForm):
    class Meta:
        model = admin
        fields = []

class AdmitPatient(forms.ModelForm):
    endDate = forms.DateField(label='Choose A date to discharge this patient')
    endTime = forms.TimeField(label='Choose A time to discharge this patient')
    class Meta:
        model = ExtendedStay
        fields = ('endDate','endTime')

class DischargePatient(forms.ModelForm):
    class Meta:
        model = ExtendedStay
        fields = []

class TransferPatientForm(forms.ModelForm):
    class Meta:
        model = ExtendedStay
        fields = []

src/healthnet/patient/templates/patient/admitPatient.html
{% extends "base/navbar.html" %}
{% load staticfiles %}
{% block style %}
    <link type="text/css" href="{% static 'css/bootstrap-datetimepicker.css' %}" rel="stylesheet"/>
{% endblock style %}

{% block content %}


<form id="AdmitPatient" method="post" action="{% url 'patient:admitPatient' apptID %}">
        {% csrf_token %}
    <h3>Are you sure that you want to admit {{ patient.personID }} to {{ hospital }} for this reason:
    {{currAppt.reason}} </h3>
    {{ form.endDate.errors }}
    <label for="id_date_field" style="float:left;margin-top:5px;">Date [MM/DD/YYYY]:</label>

    <div class="container">
        <div class="row">
            <div class="form-group">
                <div class='col-sm-6' style="width:20%">
                    <div id="datepicker" class="input-group date">
                        <input id="id_endDate" class="form-control" name="endDate" type="text"/>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <br>

                <!--  The time field for the appointment -->
                {{ appointmentForm.aptTime.errors }}
                <label for="id_time" style="float:left;margin-top:5px;">Time [HH:MM]:</label>

                <div class="container">
                    <div class="row">
                        <div class="form-group">
                            <div class='col-sm-6' style="width:20%">
                                <div id="timepicker" class="input-group date">
                                    <input id="id_endTime" name="endTime" class="form-control" type="text"/>
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                                    </span>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <br>

    <input class='delete' type="submit" name='submit' value="Yes, admit"/>
    <a href="{% url 'appointment:view' %}">Cancel</a>
</form>




{% endblock content %}

{% block scripts %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{%static 'js/moment.min.js'%}"></script>
    <script src="{%static 'js/bootstrap-datetimepicker.js'%}"></script>
    <script type="text/javascript">
        $('#datepicker').datetimepicker({
            format: 'MM/DD/YYYY',
            showTodayButton: true
        });
    </script>
    <script type="text/javascript">
        $('#timepicker').datetimepicker({
            stepping: 30,
            viewDate: false,
            format: 'LT',
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function() {
            // Add the active class
            $('li[data-item="patients"]').addClass("active");
        });
    </script>
{% endblock scripts %}

src/healthnet/patient/templates/patient/admittedPatients.html
{% extends "base/navbar.html" %}
{% load staticfiles %}
{% load app_filters %}

{% block style %}
<!-- Page specific styling -->
<link type='text/css' href="{% static 'css/appointment.css' %}" rel='stylesheet'/>
{% endblock style %}

{% block content %}

{# {% if request|isDoctor or request|isNurse %} #}
<title>HealthNet - Discharge </title>
{# {% endif %} #}

<h1 class='helpText'>Patients admitted to {{ hospital }}</h2>
<div id='containerBlock'>
        {#{% if not request|isPatient %}#}
        <table class='table table-striped sixtyfive' style='margin: 0 auto;'>
            <th>Patient:</th>
            <th>Discharge Date:</th>
            <th>Discharge Time:</th>
            {% for stay in extendedStays %}
            <tr>

                <td> {{ stay.getPatient }}</td>
                <td> {{ stay.endDate }}</td>
                <td> {{ stay.endTime }} </td>
                {% if request|isDoctor %}
                <td>
                    <a class='confirm' href="{% url 'patient:discharge' stay.id %}"> &#x270e; Discharge</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
    </div>

{% endblock content %}

{% block scripts %}

    <script type="text/javascript">
        $(document).ready(function() {
            // Add the active class
            $('li[data-item="patients"]').addClass("active");
        });
    </script> 

{% endblock scripts %}

src/healthnet/patient/templates/patient/alreadyAdmitted.html
{% extends "base/navbar.html" %}

{% block content %}
<title> HealthNet - Error with transfer </title>
<h3 class='helpText'> This patient has already been admitted to {{ hospital }}. </h3>

<h4 class='helpText'><a class='helpText center-container' href="{% url 'patient:patientDetails' patID %}">&#9664; Click here to return to the this patient's page.</a></h4>

{% endblock %}

src/healthnet/patient/templates/patient/cannotTransfer.html
{% extends "base/navbar.html" %}


{% block content %}
<title>Transfer Failed</title>
<h3>Cannot perform a transfer with {{patient}} because they have not been admitted to a hospital yet.</h3>

<p>Return to<a href="{% url 'patient:patientDetails' patient.id%}"> patient details.</a></p>
{% endblock %}

src/healthnet/patient/templates/patient/discharge.html
{% extends "base/navbar.html" %}

{% block content %}
    <!-- Set the title of the page to be what is on the page --> 
    <title>HealthNet - Delete Appointment</title>

    <form id="DischargePatient" method="post" action="{% url 'patient:discharge' stayID %}">
        {% csrf_token %}
        <h3>{{ user.first_name }}, are you sure you want to discharge your {{currPatient}} from {{ hospital }}:
            </h3> {{ form.as_p }}
            <input class='delete' type="submit" name='submit' value="Yes"/>
        </form>
        <h3><a href="{% url 'patient:admittedPats' %}">No</a></h3>

{% endblock content %}

src/healthnet/patient/templates/patient/patientList.html
{% extends "base/navbar.html" %}

{% block content %}
<title> HealthNet - View patient list</title>

<h1 class='helpText'> View your patient list </h1>
    <table class="table table-hover">
        <tr class='table-heading'> 
            <th> Patients</th>
            <th> Actions </th>
        </tr>

        <!--Listed patients are restricted in views.py-->
        {% for pat in patients %}
        <tr>
            <td>{{pat}}</td>
            <td> <a class='neutral' href="{% url 'patient:patientDetails' pat.id%}"> View Details</a></td>
        </tr>
        {% endfor %}
    </table>

{% endblock content %}

{% block scripts %}

    <script type="text/javascript">
        $(document).ready(function() {
            // Add the active class
            $('li[data-item="patients"]').addClass("active");
        });
    </script> 

{% endblock scripts %}

src/healthnet/patient/templates/patient/patientListDetails.html
{% extends "base/navbar.html" %}
{% load app_filters %}


{% block content %}
<title> HealthNet - View patient details</title>

<table class="table table-hover" style="width:24%" align="left">
    <tr class='table-heading' colspan="2">
        <th style="width:60%">Patients</th>
        <th>Actions</th>
    </tr>

    <!--Listed patients are restricted in views.py-->
    {% for pat in patients %}
    <tr>
        <td>{{pat}}</td>
        <td><a class='neutral' href="{% url 'patient:patientDetails' pat.id%}"> View Details</a></td>
    </tr>
    {% endfor %}
</table>
<div align="right">
    <table class='table table-hover' style="width:75%" align="top">
        <tr>
            <th class='table-heading' colspan="2">User information</th>
        </tr>
        <tr>
            <th>Name</th>
            <td> {{fullName}}</td>
        </tr>
        <tr>
            <th>Email address</th>
            <td> {{email}}</td>
        </tr>
        <tr>
            <th>Phone number</th>
            <td> {{phoneNumber}}</td>
        </tr>
        <tr>
            <th>Birthday</th>
            <td> {{birthday}}</td>
        </tr>
        <tr>
            <th>Address</th>
            <td> {{addressInfo}}</td>
        </tr>
        <tr>
            <th class='table-heading' colspan="2">Hospital</th>
        </tr>
        <tr>
            <th>Current hospital</th>
            <td> {{patient_model.hospitalID|default_if_none:'No hospital information on file'}}</td>
        </tr>
        <tr>
            <th class='table-heading' colspan="2">Insurance information</th>
        </tr>
        <tr>
            <th>Insurance name</th>
            <td> {{insuranceName}}</td>
        </tr>
        <tr>
            <th>Policy number</th>
            <td> {{policyNumber}}</td>
        </tr>
        <tr>
            <th class='table-heading' colspan="2">Emergency Contact information</th>
        </tr>
        <tr>
            <th>Contact name</th>
            <td> {{emergencyContact.firstName}} {{emergencyContact.lastName}}</td>
        </tr>
        <tr>

            <th>Phone number</th>
            <td> {{emergencyContact.emergencyNumber}}</td>
        </tr>

    </table>

    <table class='table table-hover' style="width:75%" align='bottom'>
        <tr>
            <th class='table-heading' colspan="4">Prescriptions</th>
        </tr>
        {% if prescriptions %}
        <tr>
            <th>Medication</th>
            <th>Dosage</th>
            <th>Refills</th>
            <th>Prescribed by</th>
        </tr>

        {% for p in prescriptions %}
        <tr>
            <td>{{ p.medication.name }}</td>
            <td>{{ p.amount }}</td>
            <td>{{ p.refill }}</td>
            <td>{{ p.doctorID }}</td>
        </tr>
        {% endfor %}

        {% else %}
        <tr>
            <td> No prescriptions to show</td>
        </tr>

        {% endif %}

    </table>

    <table class='table table-hover' style="width:75%" align="bottom">
        <tr>
            <th class='table-heading' colspan="4">Actions</th>
        </tr>
        <tr>
            <th>Schedule appointment</th>
            <td>
                {% if request|isDoctor %}
                <a class='confirm' href="{% url 'appointment:scheduleDoctor' patient_model.id %}"> Create</a>
                {% elif request|isNurse %}
                <a class='confirm' href="{% url 'appointment:scheduleNurse' patient_model.id %}"> Create</a>
                {% endif %}
            </td>
            <th>Medical Information</th>
            <td>
                {% if patient_model.medicalID != None %}
                <a class='confirm' href="{% url 'medical:history' patient_model.medicalID.id%}"> View</a>
                {% else %}
                <a class='delete'> NEEDED</a>
                {% endif %}
            </td>
        </tr>
        {%if not request|isRoot%}
        <tr>
            <th>Transfer</th>
            <td>
                {% if patient_model.hospitalID == None %}
                {% if request|isDoctor or request|isNurse %}
                <a class='delete' href="{% url 'patient:cannotTransfer' patient_model.id%}"> Transfer</a>
                {% endif %}
                {% else %}
                {% if request|isDoctor or request|isNurse %}
                <a class='confirm' href="{% url 'patient:transferPatient' patient_model.id%}"> Transfer</a>
                {% endif %}
                {% endif %}
            </td>
            <th>Messages</th>
            <td><a class='confirm' href="{% url 'messages:send' patientID %}"> Send a Message</a></td>
        </tr>

        <tr>
            <th>Prescription</th>
            <td>
                {% if request|isDoctor or request|isNurse %}
                <a class='confirm' href="{% url 'prescription:create' patient_model.id %}"> Add a prescription</a>
                {% endif %}
            </td>
            <td></td>
            <td></td>
        </tr>
        {%endif%}
    </table>
</div>
{% endblock content %}

{% block scripts %}

<script type="text/javascript">
        $(document).ready(function() {
            // Add the active class
            $('li[data-item="patients"]').addClass("active");
        });

</script>

{% endblock scripts %}

src/healthnet/patient/templates/patient/transferConfirmation.html
{% extends "base/navbar.html" %}
{% load staticfiles %}

{% block style %}
    <link type="text/css" href="{% static 'css/bootstrap-datetimepicker.css' %}" rel="stylesheet"/>
{% endblock style %}

{% block content %}

<h3 class='helpText'> Are you sure you want to transfer {{patient}} to {{othHospital}}?</h3> 
<div class='center-container'>
	<form id="transferPatient" method="post" action="{% url 'patient:transferPatient' patID%}">
	    {%csrf_token%}
	    {{ form }}
	    <a class='neutral' href="{% url 'patient:patientDetails' patID%}">Cancel</a>
	    <input class='delete' type="submit" name='submit' value="Yes, transfer"/>
	</form>
</div>

{%endblock%}